services:
  ouroboros_1:
    image: ouroboros
    build: .
    network_mode: host
    environment:
      NAME: Kaya-Sem-1
      UDP_PORT: "8080"
      HTTP_PORT: "8082"
      BROADCAST_PORT: "8080"

  ouroboros_2:
    image: ouroboros
    build: .
    network_mode: host
    environment:
      NAME: Kaya-Sem-2
      UDP_PORT: "8081"
      HTTP_PORT: "8083"
      BROADCAST_PORT: "8080"

