basePath: /
host: localhost:8081
info:
  contact: {}
  description: A simple HTTP interface to your TCP client.
  title: TCP Client API
  version: "1.0"
paths:
  /ping:
    get:
      description: Responds with pong
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Ping the service
      tags:
      - health
swagger: "2.0"
